import React, { useState } from 'react';
import { 
  BarChart3, 
  Download, 
  TrendingUp, 
  Calendar, 
  CheckCircle2, 
  Users, 
  Award,
  Clock,
  Trash2,
  Search,
  Filter,
  School,
  AlertTriangle
} from 'lucide-react';
import { AttendanceSession, TeacherUser } from '../types';
import { ConfirmDialog, ConfirmDialogState } from './ConfirmDialog';

interface ReportsViewProps {
  currentUser: TeacherUser;
  attendanceRecords: AttendanceSession[];
  teachers: TeacherUser[];
  onClearAttendance?: () => void;
  schoolName?: string;
}

export const ReportsView: React.FC<ReportsViewProps> = ({
  currentUser,
  attendanceRecords,
  teachers,
  onClearAttendance,
  schoolName = 'ABUNE GORGORIOS SCHOOL'
}) => {
  const isTeacher = currentUser.role === 'teacher';
  const [reportType, setReportType] = useState<'attendance' | 'faculty' | 'summary'>('attendance');
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | 'present' | 'late' | 'absent'>('all');
  const [toastMsg, setToastMsg] = useState<string | null>(null);

  // Filter records: If teacher, ONLY show teacher's own records
  const scopedRecords = isTeacher 
    ? attendanceRecords.filter(r => r.teacherId === currentUser.employeeId || r.teacherName === currentUser.name)
    : attendanceRecords;

  // Confirmation dialog state for clearing report data
  const [confirmDialog, setConfirmDialog] = useState<ConfirmDialogState>({
    isOpen: false,
    title: '',
    message: '',
    onConfirm: () => {}
  });

  const showToast = (msg: string) => {
    setToastMsg(msg);
    setTimeout(() => setToastMsg(null), 3000);
  };

  const presentCount = scopedRecords.filter(r => r.status === 'present').length;
  const lateCount = scopedRecords.filter(r => r.status === 'late').length;
  const absentCount = scopedRecords.filter(r => r.status === 'absent').length;
  const total = presentCount + lateCount + absentCount;
  const attendanceRate = total > 0 ? Math.round(((presentCount + lateCount) / total) * 100) : 100;

  const handleExport = () => {
    let csv = `Institution,${schoolName}\n`;
    csv += `Generated By,${currentUser.name} (${currentUser.role})\n`;
    csv += `Export Timestamp,${new Date().toISOString()}\n\n`;
    csv += `Metric,Value\nFaculty Headcount,${isTeacher ? 1 : teachers.length}\nAttendance Rate,${attendanceRate}%\nPresent Count,${presentCount}\nLate Count,${lateCount}\nAbsent Count,${absentCount}\nTotal Logs,${total}\n\n`;
    csv += `Record ID,Date,Teacher Name,Teacher ID,Check-In Time,Status,Verification Method,Notes\n`;
    
    scopedRecords.forEach(r => {
      csv += `"${r.id}","${r.date}","${r.teacherName}","${r.teacherId}","${r.checkInTime || '-'}","${r.status}","${r.checkInMethod || 'qr'}","${r.note || ''}"\n`;
    });

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${schoolName.toLowerCase().replace(/\s+/g, '_')}_attendance_report_${reportType}.csv`;
    a.click();
    showToast('Exported analytical report to CSV.');
  };

  const handleTriggerClearRecords = () => {
    if (!onClearAttendance) return;
    setConfirmDialog({
      isOpen: true,
      title: `Erase Analytical Insights • ${schoolName}`,
      message: `Are you sure you want to completely erase and reset Analytical Insights • ${schoolName} School Attendance & Faculty Analytics? All attendance records will be cleared.`,
      confirmText: 'Yes, Erase Analytics & Attendance Logs',
      cancelText: 'Cancel',
      variant: 'danger',
      onConfirm: () => {
        onClearAttendance();
        showToast(`Analytical Insights for ${schoolName} cleared successfully.`);
      }
    });
  };

  const filteredLogs = scopedRecords.filter(r => {
    const matchSearch = 
      r.teacherName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      r.teacherId.toLowerCase().includes(searchTerm.toLowerCase()) ||
      r.date.includes(searchTerm);
    const matchStatus = statusFilter === 'all' || r.status === statusFilter;
    return matchSearch && matchStatus;
  });

  return (
    <div className="space-y-6 animate-in fade-in duration-300 pb-12">
      {/* Confirm Dialog */}
      <ConfirmDialog 
        state={confirmDialog} 
        onClose={() => setConfirmDialog(prev => ({ ...prev, isOpen: false }))} 
      />

      {toastMsg && (
        <div className="bg-slate-900 text-white px-4 py-3 rounded-2xl shadow-xl flex items-center justify-between border border-slate-700">
          <div className="flex items-center space-x-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span className="text-xs font-bold">{toastMsg}</span>
          </div>
          <button onClick={() => setToastMsg(null)} className="text-xs text-slate-400 hover:text-white cursor-pointer">✕</button>
        </div>
      )}

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2 text-blue-600 font-semibold text-xs uppercase tracking-wider">
            <BarChart3 className="w-4 h-4" />
            <span>Analytical Insights • {schoolName}</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight mt-1">
            School Attendance & Faculty Analytics
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 mt-1">
            {isTeacher 
              ? `Personal attendance analytics, punctuality metrics, and audit log for ${currentUser.name}.`
              : `Historical attendance trends, departmental performance, and exportable audit logs for ${schoolName}.`}
          </p>
        </div>

        <div className="flex items-center gap-2.5 self-start sm:self-auto flex-wrap">
          {onClearAttendance && (
            <button
              onClick={handleTriggerClearRecords}
              className="inline-flex items-center gap-1.5 px-3.5 py-2.5 bg-rose-50 hover:bg-rose-100 text-rose-700 border border-rose-200 text-xs font-bold rounded-xl shadow-xs transition-colors cursor-pointer"
              title="Erase Report Data"
            >
              <Trash2 className="w-4 h-4" />
              <span>Erase Analytical Insights</span>
            </button>
          )}

          <button
            onClick={handleExport}
            className="inline-flex items-center gap-1.5 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl shadow-xs transition-colors cursor-pointer"
          >
            <Download className="w-4 h-4" />
            <span>Export Analytics Report</span>
          </button>
        </div>
      </div>

      {/* 4 Summary Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
          <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
            {isTeacher ? 'My Attendance Rate' : 'Faculty Attendance Rate'}
          </span>
          <div className="mt-2 flex items-baseline justify-between">
            <span className="text-3xl font-black text-blue-600 font-mono">{attendanceRate}%</span>
            <span className="text-[11px] font-bold text-blue-700 bg-blue-50 px-2 py-0.5 rounded-full">
              {total} Logged
            </span>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
          <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">On-Time Check-ins</span>
          <div className="mt-2 flex items-baseline justify-between">
            <span className="text-3xl font-black text-emerald-600 font-mono">{presentCount}</span>
            <span className="text-[11px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full">
              Verified
            </span>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
          <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Delayed / Late</span>
          <div className="mt-2 flex items-baseline justify-between">
            <span className="text-3xl font-black text-amber-600 font-mono">{lateCount}</span>
            <span className="text-[11px] font-bold text-amber-700 bg-amber-50 px-2 py-0.5 rounded-full">
              Logs
            </span>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
          <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
            {isTeacher ? 'My Profile' : 'Faculty Roster'}
          </span>
          <div className="mt-2 flex items-baseline justify-between">
            <span className="text-3xl font-black text-slate-900 font-mono">
              {isTeacher ? '1' : teachers.length}
            </span>
            <span className="text-[11px] font-bold text-slate-700 bg-slate-100 px-2 py-0.5 rounded-full">
              {isTeacher ? currentUser.employeeId : 'Accounts'}
            </span>
          </div>
        </div>
      </div>

      {/* Breakdown Overview - Show only for Managers */}
      {!isTeacher && (
        <div className="bg-white rounded-3xl p-6 border border-slate-200 shadow-xs space-y-4">
          <h3 className="text-base font-black text-slate-900">Departmental Compliance Overview</h3>
          <p className="text-xs text-slate-500">Attendance punctuality across academic departments</p>

          <div className="space-y-3 pt-2">
            {[
              { name: 'Mathematics & STEM', rate: 98, faculty: 6 },
              { name: 'Physical Sciences & Chemistry', rate: 96, faculty: 5 },
              { name: 'Languages & Humanities', rate: 94, faculty: 4 },
              { name: 'Fine Arts & Physical Ed', rate: 95, faculty: 3 }
            ].map((dept, idx) => (
              <div key={idx} className="p-4 bg-slate-50 rounded-2xl border border-slate-100 flex items-center justify-between">
                <div>
                  <h4 className="text-xs font-bold text-slate-900">{dept.name}</h4>
                  <p className="text-[10px] text-slate-400">{dept.faculty} Faculty Members</p>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-32 bg-slate-200 rounded-full h-2 overflow-hidden hidden sm:block">
                    <div className="bg-blue-600 h-full rounded-full" style={{ width: `${dept.rate}%` }} />
                  </div>
                  <span className="font-mono font-bold text-xs text-blue-700">{dept.rate}%</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Attendance Audit Log Table */}
      <div className="bg-white rounded-3xl p-6 border border-slate-200 shadow-xs space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h3 className="text-base font-black text-slate-900">Attendance Audit Records</h3>
            <p className="text-xs text-slate-500">Search, verify, or audit individual teacher attendance entries</p>
          </div>

          <div className="flex items-center gap-2">
            <div className="relative">
              <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                placeholder="Search by teacher or date..."
                className="pl-8 pr-3 py-1.5 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value as any)}
              className="px-2.5 py-1.5 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-800 font-semibold focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="all">All Statuses</option>
              <option value="present">Present Only</option>
              <option value="late">Late Only</option>
              <option value="absent">Absent Only</option>
            </select>
          </div>
        </div>

        {filteredLogs.length === 0 ? (
          <div className="p-8 text-center bg-slate-50 rounded-2xl border border-slate-100 text-slate-400 text-xs">
            No attendance records found matching the current query.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-slate-200 text-slate-400 uppercase font-bold text-[10px]">
                  <th className="py-2.5 px-3">Date</th>
                  <th className="py-2.5 px-3">Teacher</th>
                  <th className="py-2.5 px-3">Employee ID</th>
                  <th className="py-2.5 px-3">Check-In Time</th>
                  <th className="py-2.5 px-3">Status</th>
                  <th className="py-2.5 px-3">Verification Method</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filteredLogs.map(log => (
                  <tr key={log.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="py-3 px-3 font-mono text-slate-600 font-medium">{log.date}</td>
                    <td className="py-3 px-3 font-bold text-slate-900">{log.teacherName}</td>
                    <td className="py-3 px-3 font-mono text-indigo-600">{log.teacherId}</td>
                    <td className="py-3 px-3 font-medium text-slate-700">{log.checkInTime || '-'}</td>
                    <td className="py-3 px-3">
                      <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase ${
                        log.status === 'present' 
                          ? 'bg-emerald-100 text-emerald-800' 
                          : (log.status === 'late' ? 'bg-amber-100 text-amber-800' : 'bg-rose-100 text-rose-800')
                      }`}>
                        {log.status}
                      </span>
                    </td>
                    <td className="py-3 px-3 text-slate-500 font-medium capitalize">
                      {log.checkInMethod === 'qr' ? 'QR Station Scan' : (log.checkInMethod || 'QR Verification')}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

