export type AttendanceStatus = 'present' | 'late' | 'absent' | 'excused';

export interface TeacherUser {
  id: string;
  name: string;
  email: string;
  employeeId: string;
  passwordHash?: string; // SHA-256 / hashed password
  passwordSalt?: string;
  rawPassword?: string; // Real/plain active password
  currentPassword?: string; // Real/plain active password
  department: string;
  mentorName?: string;
  mentorId?: string;
  role: 'teacher' | 'manager' | 'qr_station' | 'mentor' | string;
  avatarUrl?: string;
  avatar?: string;
  phone?: string;
  roomNumber?: string;
  subjects?: string[];
  subject?: string;
  assignedClasses?: string[];
  shiftTiming?: string;
  joinDate?: string;
  status?: 'active' | 'inactive' | 'on_leave' | 'leave';
}

export interface DepartmentItem {
  id: string;
  name: string;
  code?: string;
  headOfDepartment?: string;
  headTeacher?: string;
  teacherCount: number;
  subjectList?: string[];
  subjects?: string[];
  totalSubjects?: number;
  color?: string;
  description?: string;
}

export type Department = DepartmentItem;

export interface AttendanceTimeSettings {
  morningStart: string; // e.g. "07:30 AM" or "07:30" (Create Time / Post Time)
  morningEnd: string; // e.g. "09:30 AM" or "09:30" (Stop Time)
  lateThreshold: string; // e.g. "08:15 AM" or "08:15" (Late Time Cutoff)
  createTime?: string; // e.g. "07:30" or "07:30 AM"
  lateTime?: string; // e.g. "08:15" or "08:15 AM"
  lateAfterMinutes?: number; // e.g. 15 (Present within first X minutes, Late after X minutes)
  stopTime?: string; // e.g. "09:30" or "09:30 AM"
  qrDefaultExpiryMinutes: number; // e.g. 120
  enforceOneScanPerDay: boolean;
  gracePeriodMinutes: number;
  autoSendQREnabled: boolean;
  autoSendTime: string;
  broadcastTarget: 'single_kiosk_device' | 'all_devices';
  targetDeviceName: string;
}

export interface BroadcastQR {
  id: string;
  token: string;
  title?: string;
  label?: string;
  generatedDate: string; // "YYYY-MM-DD"
  createdAt?: number;
  generatedAt?: number;
  postTime?: string; // e.g. "07:30 AM" or "07:30" (Create Time)
  createTime?: string; // e.g. "07:30" or "07:30 AM"
  lateTime?: string; // e.g. "08:15" or "08:15 AM"
  lateAfterMinutes?: number; // e.g. 15 (minutes from start)
  stopTime?: string; // e.g. "09:30 AM" or "09:30"
  expiresAt: number;
  durationMinutes?: number;
  isActive: boolean;
  notes?: string;
  generatedBy?: string; // "Academic Manager"
  generatedByRole: 'manager';
  targetDevice?: string;
  isAutoGenerated?: boolean;
  revokedAt?: number;
  status?: 'active' | 'expired' | 'revoked';
  scanCount?: number;
  managerSignature?: string;
}

export interface AttendanceSession {
  id: string;
  date: string; // YYYY-MM-DD
  sessionPeriod?: 'full' | 'morning' | 'afternoon';
  status: AttendanceStatus;
  checkInTime: string; // e.g. "08:04 AM"
  checkInMethod?: 'qr' | 'manual' | 'link';
  mentorName?: string;
  sessionTitle?: string;
  room?: string;
  note?: string;
  teacherId?: string;
  teacherName?: string;
  qrStationId?: string;
}

export interface Announcement {
  id: string;
  title: string;
  content: string;
  author: string;
  authorRole: string;
  date: string;
  priority: 'urgent' | 'normal' | 'info';
  category: 'Faculty Notice' | 'Mentor Bulletin' | 'Schedule Update' | 'Training' | 'General';
  isRead?: boolean;
  pinned?: boolean;
}

export interface ManagerFeedback {
  id: string;
  teacherId: string;
  teacherName: string;
  category: 'Attendance Clarification' | 'Schedule & Duty' | 'Classroom / Tech Issue' | 'General Note' | 'Urgent Inquiry' | string;
  subject: string;
  message: string;
  priority: 'normal' | 'urgent';
  createdAt: string;
  status: 'pending' | 'resolved' | 'sent' | 'reviewed';
  managerReply?: string;
  response?: string;
  repliedAt?: string;
}

export interface SchoolClass {
  id: string;
  name: string; // e.g. "Mathematics - Grade 9A"
  grade: string; // "Grade 9A"
  section?: string;
  subject: string; // "Mathematics"
  studentCount: number;
  teacherName?: string;
  teacherId?: string;
  timeSlot?: string; // "08:30 AM"
  nextPeriodTag?: string; // "Next Period"
  color?: 'purple' | 'blue' | 'orange' | 'teal' | 'emerald' | string;
  room?: string;
  roomNumber?: string;
  schedule?: string;
  performanceAverage?: number;
  attendanceRate?: number;
}

export type ClassItem = SchoolClass;
export type ClassSection = SchoolClass;

export interface ScheduleItem {
  id: string;
  dayOfWeek: string;
  period: string | number;
  startTime: string;
  endTime: string;
  title?: string;
  subject?: string;
  grade?: string;
  section?: string;
  room: string;
  teacherName?: string;
  teacherId?: string;
  status?: 'In Progress' | 'Next' | 'Upcoming' | 'Completed' | string;
  color?: string;
  notes?: string;
}

export type TimetableSlot = ScheduleItem;

export interface TodoItem {
  id: string;
  title: string;
  subtitle?: string;
  dueDate?: string;
  dueStatus?: 'Due Today' | 'Due Tomorrow' | 'Due May 22' | 'Due May 25' | 'Upcoming' | 'High' | 'Medium' | 'Low' | string;
  priority?: 'High' | 'Medium' | 'Low';
  isCompleted?: boolean;
  completed?: boolean;
  type?: 'assignment' | 'test' | 'worksheet' | 'report' | 'task';
  text?: string;
}

export interface StudentRecord {
  id: string;
  name: string;
  rollNumber?: string;
  studentId?: string;
  grade: string;
  attendanceStatus?: 'present' | 'absent' | 'late' | 'excused';
  attendanceRate?: number;
  isLocked?: boolean;
  lockedAt?: string;
  avatarUrl?: string;
  avatar?: string;
  gender?: string;
  parentPhone?: string;
  lastScore?: string;
  email?: string;
  classId?: string;
  className?: string;
  averageGrade?: string | number;
}

export type StudentItem = StudentRecord;
export type Student = StudentRecord;

export interface Assignment {
  id: string;
  title: string;
  classId?: string;
  className?: string;
  subject?: string;
  dueDate: string;
  postedDate?: string;
  targetTeacherType?: 'all' | 'specific';
  targetTeacherId?: string; // "All" or teacher employeeId/id
  targetTeacherName?: string; // "All Teachers" or teacher name
  evaluationType?: 'accept_reject' | 'points';
  maxPoints?: number;
  totalPoints?: number;
  description?: string;
  status?: 'active' | 'closed' | 'draft' | string;
  submittedCount?: number;
  submissionsCount?: number;
  totalStudents?: number;
  createdBy?: string;
}

export type AssignmentItem = Assignment;

export type AssignmentSubmission = {
  id: string;
  assignmentId: string;
  assignmentTitle: string;
  teacherId?: string;
  teacherName: string;
  teacherEmail?: string;
  teacherDepartment?: string;
  submittedAt?: string;
  submittedDate?: string;
  submissionText?: string;
  submissionMethod?: 'online' | 'in_person';
  fileName?: string;
  fileUrl?: string;
  evaluationType?: 'accept_reject' | 'points';
  status?: 'pending' | 'accepted' | 'rejected' | 'graded' | 'Submitted' | 'Pending Review' | string;
  score?: number;
  maxScore?: number;
  totalScore?: number;
  managerFeedback?: string;
  feedback?: string;
  reviewedAt?: string;
  reviewedBy?: string;
  className?: string;
  classGrade?: string;
  studentId?: string;
  studentName?: string;
  studentAvatar?: string;
};

export type SubmissionItem = AssignmentSubmission;

export interface MaterialItem {
  id: string;
  title: string;
  className: string;
  subject: string;
  fileType: string;
  fileSize: string;
  uploadedDate: string;
  downloadUrl?: string;
}

export interface GradeRecord {
  id: string;
  studentId: string;
  studentName: string;
  className: string;
  assessmentTitle: string;
  score: number;
  letterGrade: string;
  date: string;
}

export type NavTab = 
  | 'login'
  | 'dashboard'
  | 'classes'
  | 'students'
  | 'teachers'
  | 'subjects'
  | 'attendance'
  | 'timetable'
  | 'materials'
  | 'announcements'
  | 'feedback'
  | 'feedback_view'
  | 'messages'
  | 'profile'
  | 'assignments'
  | 'my_tasks'
  | 'teacher_tasks'
  | 'submissions'
  | 'teacher_submissions'
  | 'grades'
  | 'exams'
  | 'reports'
  | 'settings'
  | 'users'
  | 'audit'
  | 'manager_dashboard'
  | 'manager_teachers'
  | 'manager_password_resets'
  | 'manager_departments'
  | 'manager_attendance'
  | 'qr_station'
  | 'qr_broadcast'
  | 'qr_scanner'
  | 'qr_logs'
  | 'qr_manual_checkin'
  | 'qr_settings';

export type ActiveTab = NavTab;
export type SidebarTab = NavTab;

export interface PasswordResetRequest {
  id: string;
  teacherId: string;
  teacherName: string;
  email: string;
  department?: string;
  requestedNewPassword?: string;
  status: 'pending' | 'approved' | 'rejected';
  requestDate?: string;
  requestTime?: string;
  requestedAt?: string;
  approvedAt?: string;
  reason?: string;
  resolvedAt?: string;
  resolvedBy?: string;
  managerNotes?: string;
}
